pipeline {
  agent any

  environment {
    IMAGE_TAG = ${BUILD_NUMBER}
  }

  stages {
    stage ('Checkout') {
      steps {
        git url: https://github.com/shree1434/Docker-Zero-To-Hero,branch: 'main'
      }
    }

    stage ('Build Docker') {
      steps {
        script {
            sh '''
        echo 'Build Docker Image'
        docker build -t shree1434/python_django:${IMAGE_TAG} .
        '''
        }
      }
    }

    stage ('Push Docker Image') {
      steps {
        script {
            sh '''
            echo 'Push the docker image to repo'
            docker push shree1434/python_django:${IMAGE_TAG}
            '''
        }
      }
    }

    stage ('Deploy to Docker') {
      steps {
        script {
            sh '''
            echo 'Deploying to Docker'
            docker stop new-app||true
            docker rm new-app||true
            docker run -d --name new-app -p 8000:8000 shree1434/python_django:${BUILD_NUMBER}
            '''
        }
      }
    }
  }
}
